services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Codemacher\TileProxy\:
    resource: '../Classes/*'

  Codemacher\TileProxy\Controller\TileProxyController:
    public: true

  Codemacher\TileProxy\Controller\NominatimProxyController:
    public: true    